name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  windows:
    name: Build and Publish
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Nuke build
        run: ./.nuke/build.cmd Compile PublishGitHub --GitHubToken ${{ secrets.GITHUB_TOKEN }}